classdef Config < Object.Object
    properties
        calibrationTargetSize
        calibrationTargetWidth
        calibrationType
        fixationUpdateInterval
        fixationUpdateAccumulate
        dataFileName
        fileEventFilter
        fileEventData
        fileSampleData
        linkEventFilter
        linkEventData
        linkSampleData
        recordedEye
        parserConfiguration
        dummyMode
    end
end